version: '3.7'
services:
  procservcontrol:
    image: lnlscon/procservcontrol:v1.6
    hostname: ioc
    build:
        dockerfile: 'Dockerfile'
        context: .
        labels:
            - "br.com.lnls-sirius.description=procServ Control"
            - "br.com.lnls-sirius.department=CONS"
            - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
    environment:
      - PORT=20110
    dns:
      - 10.0.0.71
      - 10.0.0.72
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
